version: '3'
services:
  ursho:
    restart: always
    image: godlzr/ursho:df069306b87c955752d4e684c5cf07cef43f5655
    ports:
      - 8080:8080
    depends_on:
      - app_postgres
  app_postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 'mypass'
      POSTGRES_USER: 'ursho_db'
      POSTGRES_DB: 'ursho_db'
    ports:
      - 5432:5432
